# Generated by Django 5.1.4 on 2024-12-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
